application: chirpradio
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

# Always use HTTPS for pages related to authentication & user management
- url: /auth/.*
  secure: always
  script: main.py

- url: /.*
  script: main.py
